tweets = ['Masturbating with a man who clearly does not live close by',
          "I've been having fun today but then I start feeling really bad for blowing the opportunity to have a family",
          'I want to be the one in charge of all the new cars',
          'Youre a bitch to the fact that because you have a child the family unit is broken',
          'Me making a Star Wars clone costume and then squirting paint alcohol into my mouth while hiding under my bed. That was beautiful.',
          'Is it wrong to hurt an lover? Because when you do! then things cool a lot better',
          'I hate board games for the usual reason',
          'The birds dont die every time I put a lemon in a soup flame',
          'My younger brother is mean to me... he stuffs his guitar with marijuana. Can someone explain why?',
          'Why do friendly-housing meetings become "Have a great week" type discussions?',
          'Muted colors kickoff the spectacle of publicizing private conversations',
          'My sweetie and I are doing okay today and tomorrow',
          'News broke this week that my ex had been cheating on me for four years and I had to drop the bombshell and pretend I was his ex',
          'I always turn off phone and TV in my house so I can do a little domesticating and watch some giggles',
          'I just put my finger on Alex again and Im like this is really cool',
          'Sometimes I have to push my arm up my ass to open a can of coleslaw',
          'Big brother is having a little fun at Taco Bell',
          'Big brother is laughing at his fistful of food right now',
          'Do you want a daddy and a titty or not',
          'I want to know what people opinionof people who have kids. Do they like who they see on the Internet or do they not?',
          "Just got taunted by my ex and I think I'm beautiful",
          'I want a big sloppy popper',
          'Im a professional',
          'Im on the phone and I want to shoot it all over your phone',
          'Andrew isnt yourself Andrew is who he is - a sick caricature of a man',
          'Donut lane. I want to take it. Take it fast',
          '']
