tweets = ['Remembering is forgotten..... keef keef',
          'Asking all my bosses to let me smoke in the bath',
          'Sara explains to me how to train your ass:   1. Stretching your legs   2. Stretching your abs   3. Stretching your pubes   4. Stretching your pubes  5. Stretching your pubic hair',
          'Sometimes when I take my tacos out and put my steak on the coffee table everyone is like what flavor',
          'I cant wait to get my ass taken care of quick swift',
          'Im raised Catholic',
          'I turn my back on women who sabotage my goals by making me do my homework',
          'Jessica is wasted out of her little damn mind',
          'Im a bad girl a boy and a man',
          'Gonna take a deep breath and think about my ex',
          'Thats how you know Andrew and I are really in love because were doing our thing a) Have a boob b) We can hang out for a lil bit c) We both get it so why should we?',
          'Sitting in the shower eating a crab and watching as my juul heals I want so much food. The one and only',
          'Am leaving California to go live on Instagram',
          'Im in the car driving',
          'Hey guys, Im doing some type of thing right now: I- am putting away my dong and taking my Lexapro. Just got an e-mail',
          'In the morning fucking drive to work?',
          'Sometimes you gotta take that Gatorade bite out of your mouth and make the sweetest sounds youve ever heard',
          'All my life pressing my lips against my bottom lip as you stroke a computer',
          'I want to date a professional singer. But first I want to get my hair cut and my butt carved by my beautiful wife',
          'There is nothing else to do but get pebbles in town',
          'Do i have to go to work to get an erection? The think is yes',
          'Wearing a t-shirt that read DESTROY YOUR LITTLE BIRTHDAY',
          ]
