tweets = ['You cant make chili without cooking the garlic',
          'Oh my god. I could have gone with the juul cream cheese on the fresh mozzarella',
          'I have two boys and a horny sister and after two days of being absolutely boner-free (Ive cried) I can finally stop pretending',
          'Love how jealous I am of everyone who has made my day',
          'Just nails for me',
          'I could smoke my wand and not be sad',
          'Im so sick of constantly repressing and minimizing',
          'Everyday is like this: You can never remember all the ways in which you had to die at slaughterhouses',
          'You can say dill pick up on it',
          'Instagramming my friends about how I get all these cute little instagram pics of my lovely boobs',
          'Cant wait to start lunch because I had a bad one',
          "Didn't mean to upset anyone",
          'Just put a guy in the middle of the road and make it a tea and coffee situation. He can thank you later',
          'Kind of insane believing I can become a daughter of my own brain washing podcast personality acquisition program',
          'Im so cool but people would be so mean to me',
          'Kindergardens full of strippers',
          'Theres really no reason to complain about being bored when you can go to bed at night',
          'No one should ever question my health or my love for fashion',
          'Expectations',
          'Why dont we make a twinkly coin',
          'Why dont we make a fucking hole in the ground',
          'Would you be willing to take my word for it by taking my word for it that if something amazes you feel free to tell me',
          'No reason to fuck anyone up like this field is for sale',
          'My right nostril is doing the talking here',
          'Little did I know I would become one of them',
          'Like a Prayer is one of those songs where you can be doing any menial task but if its not for the help of your ex it might as well end up in a bucket',
          'Me and my physical therapist have been having a good time of our own',
          'I could be doing journaling or I could just be doing taking my shirt off',
          'You can say whatever you want about my style (punk vocals)']
