tweets = ['Wait what?? Andrew is that guy who just happens to put his finger on the perfect word and says things like "Okay I just got really really really high but I think it might be time to swap lives with a mama threesome',
          'Yes I did say Andrews calm, collected & kind of powerful enough to get me to listen to the new Bob Dylan album',
          'You are being watched over by evil little boys',
          'I dont like cuddly people, maybe get over it',
          'Im going to get down to my titties and get my act together',
          'Do I look like a parakeet or a cantaloupe? I want to have a domino effect',
          'I think Im using too much corn syrup on Instagram',
          'Ive been shaved and dicked three times in a row',
          'I didnt just want to hangout with my ex - I wanted to date someone with my usual sense of entitlement',
          'The more people I hangout with the sweeter my libido is',
          'One day I gravitate to poppers, and the next I take my laxatives',
          'Its like Christmas in that I have a precariously empty saucer after the fact',
          'Me seeking attention through Instagram posts and text messages',
          "New Year's Eve everyone",
          'I love how much juice my Diet Coke has.',
          '#juezerhciallspicayacotle',
          'I had a craving for a good, full-flavored jalapeno. I had a craving. I had a craving. I had a craving!!!',
          'Told myself I did every task I could do to make sure no one was made to feel bad',
          'You can take a dab and read a book at the same time but you wont fuck up my day',
          'Keep telling yourself you are, you are. The list can get long and thirsty. He has a big nose and big hands. He tells me I look like shit and he thinks I am. I tell him I am fine and he says I am not. He tells me he has had his period and I am fine and he goes away. He told me the next day when I take my shower I will be fine. He tells me I have to get a high-five and he is going to fuck me now and then',
          'I want to hangout with Bobby but I instead find myself running out of drinks',
          'If Im going to do something dumb like wear a tennis cap to business today lets do it',
          'Ive got my earbuds on Im doing tv show lol',
          'It pains me to see me disappointed',
          'I dont believe in banjo playing',
          'Did you just tell me to put my vibrator on the bed and put the juul in my ew I did',
          'My family makes for a really bad family',
          'My holes are filled with bitches wait a minute!',
          'Cool artwork thing everyones looking pretty in the gallery',
          'The media is killing me fast shaming me for liking the new album',
          'ttclub is shaping up pretty damn good for you sweetie',
          'Dr dick wait wait wait wait wait wait wait.... wait wait!!',
          'This girl on tinder is obviously not her sister',
          'Me: what are you doing',
          'Im making coffee by myself with boneless hands and giant mitts',
          'Me and my Dr Pepper dream girl do hit the street once a week for at least a month. We jack off and laugh about banh mi',
          'My family all collectively dunking on a fruity beverage that leaves a fruity taste in their throats',
          'I cook. One bite at a time. Perfect.',
          "I want a steak and a potty party. Hasn't happened yet but I want itDDD",
          'My toes are touching so much when I inhale',
          'Cant wait to get my hands dirty...well done.',
          'Baby I am looking for like me (21) 205-cropped, 100% of what I do is love with girls (35) 205-pecan, 205-cinnamon, 205-cinnamon cuz girls like them none of the boring shit',
          ]
